### ISSUE TITLE
Display problems to be corrected

### ISSUE THREAD

**Issue by Dariosky-01** [mchlnix/SMB3-Foundry#104]
In the original level 1-3 you can see that there are two design errors.
These shouldn't be mistakes in my opinion and
I explain why.
One of these errors is related to the superimposition of an object on top of another but this must necessarily be on top because it serves to open a way above where it is placed, a road above the walkable object.
This object that specifically I mean "Water - 2 Blocks High" and which is found as an error in the original level 1-3, as seen in the project, in potion X 122 and Y 26, is above the walkable object called "Orange Block Platform "and above it is not displayed by the hacker modification, whether it is there or on top of another object.
This flaw is also visible for other similar editing objects such as "Water - Horizontally Oriented", "Water - Vertically Oriented", "Wired Background", "Wired" and "Wired Blue Background"
These that overlaid with other objects have a transparency function inside the game, should be seen as openings above other objects in the project, i.e. in a way that they make the air they occupy above the objects where they are placed in the level you are making the hacker modification because this is the effect they will have in the game and it is also a way to detect it in the project in some way without losing sight of it.
Obviously to avoid losing it inside the background it would be better if its border was drawn or dashed, or in black or red.

There is a display problem in the "Invisible Coin" and "Invisible 1-Up" icons but only in the icons of the left tool window, they cannot be distinguished just like the icons mentioned above.

The simple "Bricks" or that return objects, even these are not distinguished and they are a lot, this slows down the search among those who do not know the position, or the objects present in the "recent" tab.
Same goes for the "?" Objects.

Still in the original project in level 1-3 it is right that the object I am about to talk about is considered an error, but the object in question which is the one in position X 127 and Y 12 and is "Orange Block Platform", has as a minimum, horizontally at the moment it is chosen and added in the project, two 2x2 terrestrial ones placed horizontally, and this creates the error in the original project 1-3, because this being placed in the last "column" of point X, it exits out of the project view, and this creates an error, to solve this error it should start as a size with a minimum of 2x2, with only one tile and not with two horizontal tiles of 2x2.

In the specific of this "water" level I noticed you can't see the "P-Swich" image in the icons.

In level 1-2 instead there is an error in the icons of the pipes, there are icons dedicated to "Leftward Pipe" and "Rightward Pipe" for both "Can Go In" and "Can't Go In" with icons are not visible as normal lying tubes on the right or left and as they are seen incorrect in the icons they are seen inside the project if chosen to position them.

**Comment by Dariosky-01** [comment]
Images to better understand
![IMG_20210424_030915](https://user-images.githubusercontent.com/81451904/115943030-d680e100-a4ad-11eb-9076-671f00e949db.jpg)
![1](https://user-images.githubusercontent.com/81451904/115943034-dd0f5880-a4ad-11eb-8329-62fff58cccab.PNG)
![2](https://user-images.githubusercontent.com/81451904/115943038-e698c080-a4ad-11eb-98a2-6dcbc7e212a2.PNG)
![9](https://user-images.githubusercontent.com/81451904/115943039-eac4de00-a4ad-11eb-9fac-ed88ef8ada3a.PNG)
![3](https://user-images.githubusercontent.com/81451904/115943041-eef0fb80-a4ad-11eb-940c-5eb52b8af920.PNG)
![4](https://user-images.githubusercontent.com/81451904/115943045-f4e6dc80-a4ad-11eb-9de6-9825dc946fe2.PNG)

**Comment by mchlnix** [comment]
The invisible objects should be fixed. The water sometimes not being drawn is a problem, since the block there is sometimes used to be invisible, sometimes to block out stuff as in this level. It's not easy to know which one it is.

That's why there is a separate View option, which lets you toggle the behavior.
