### ISSUE TITLE
Export Level to ASM

### ISSUE THREAD

**Issue by BlueFinch3000** [mchlnix/SMB3-Foundry#109]
Idea: 
This idea allows exporting of a level's object and enemy data to their respective ASM files.

Problem it solves: 
It mitigates the extra steps we often take of saving an m3l then importing it. Since romhacks that become more technical often demand going back to source code so often, this would alleviate the burden of extraneous work.

Implementation: 
For sheer simplicity's sake, perhaps even force using the default directory structure / file names of the southbird disassembly?

Menu Option Ideas:
1)Level ASM Export: uses the default files for the current level being edited to save the ASM data to.

2)Custom Level ASM Export:
Let's user choose which files get overwritten / where files get saved. Maybe do some simple validation to make sure it is a legitimate place to export if it is going to overwrite an existing file?

**Comment by mchlnix** [comment]
Implemented
