### ISSUE TITLE
Prioritize Desirable Features

### ISSUE THREAD

**Issue by BlueFinch3000** [mchlnix/SMB3-Foundry#110]
A plea:
Please prioritize features that will get things moving and get people completely onboard with Foundry. 
This project started 2 years ago, and it has come a long way. Lately, it seems like the changes have become increasingly small. Yet there are still large features that haven't been implemented, like overworld map editor.
I feel like this is a good time to zoom out, look at the project as a whole, and refocus on the original intent which was to be a one-stop solution that could replace all older and out-of-development programs.
I am an active part of the community so please don't take this as uneducated criticism or that I am demanding something from devs who do this in their spare time.
I simply think we need to zoom out and refocus on the central mission.
Thanks for coming to my TedX Talk.

**Comment by mchlnix** [comment]
Overworld editor sans locks and pipes is available.

**Comment by BlueFinch3000** [comment]
Nice. I will look at it as soon as I can. Awesome work, sir.
