### ISSUE TITLE
Windows Explorer update when "open" command is chosen

### ISSUE THREAD

**Issue by Dariosky-01** [mchlnix/SMB3-Foundry#112]
When searching for .rom files the explorer window always opens in the same location, the location is a folder that is created for Foundry in "%temp%" of the Winfows system.

It would be more useful if Foundry, upon opening, opened the last path I used instead of always the usual one inside "%temp%".

The last path is given only to the explorer to search for the emulator software to be set in the Foundry options,
why doesn't the same happen to search for .rom files?

It seems to be done on purpose to annoy.

**Comment by mchlnix** [comment]
I'm not 100% sure what you mean, but you can now configure the directory the open-file-dialog starts at in the editor settings.
