### ISSUE TITLE
Added a custom option in Foundry to choose where to create its workbook in "%temp%".

### ISSUE THREAD

**Issue by Dariosky-01** [mchlnix/SMB3-Foundry#113]
There is a small problem with the folder you create in Windows "%temp%" relative to the use of Foundry.
I happened to have the hard disk "c: \" the one with the operating system full, and therefore I had both problems opening Foundry, and problems during the hacker modification, in practice I was modifying a level but at a certain dot Foundry took up the little space I had left on my hard drive without my being able to realize it and allowed the .rom file I was editing to get corrupted. That this was caused by me immediately and I had confirmation through Joe Smo after explaining the problem as I am explaining it now here, so it would be useful if in the Foundry options you could change the path destined for the folder you create in "%temp%" of Windows for its work, also because, from what I could understand it always creates new signs in there and they can also be huge, very heavy in MB, so it would be very useful to be able to have more control of these folders creates, adding an option to set the preferred folder.
Also to avoid the risk of corrupting the .rom file, it is better to set up a hard disk with much more space, and if there is no space.

Also adding a window notifying the lack of space and advising to change this path to avoid corrupting the file with the command save to a full hard disk.

**Comment by mchlnix** [comment]
I see the problem, but the temp folder the data is extracted to is what the operating system wants. And after closing the editor those files get deleted again.

It certainly is an edge case, that there is no hard drive space left, so I wouldn't want to implement changing things like that. I would rather advise configuring the operating system in a way, that the temp folder is on a partition with enough hard drive space.
