### ISSUE TITLE
Gathering of the level and map jump system into a single system

### ISSUE THREAD

**Issue by Dariosky-01** [mchlnix/SMB3-Foundry#116]
I was making some considerations of the classic game how it works in regards to bridges connecting levels.
Being a game in practice where this function is the basis of operation, I think it is limiting to consider the possibility of putting only one possible bridge as an option to exit the level.
I think it was not made better than this in the original version because we did not want to complicate the game the kids used to play in those days, to be a game within everyone's reach as a difficulty, but here we are not children or kids, we are people we want the maximum, and if possible, to be able to play with maximum complication, even logical, to be more of a game, this of SMB3, suitable for the most tenacious and fierce, a game more suitable for those more experienced and competitive people if desired, I am one such.
That's why I'm here and I want to propose this idea, I want to propose a very interesting change that will forever change the experience of those who will play the new .rom hacks created after this change (if it is implemented), and will also change the editing experience for hackers because they will no longer be limited in their projects.

What should change should be simple to understand so I will try as much as I can, be brief.
It's simple to understand, but I don't know if it's possible to add just everything, but I hope for everyone it is.

Start.

In Foundry it is possible to set only one level, when you allocate a pipe for the level change which will then allow you to complete the second chosen level (which would become part of the first) to exit at the point where you entered the map to change the status of the "4x4" tile representing the level, from playable and locked (to move Mario forward in the road) to completed level with the possibility of scrolling in the road of the map.

Now, what is in practice I ask is that you give way to choose several levels to be allocated as levels accessible through different bridges (not just one) but which are set for each tube through the changes in the "Jump Editor" window.

In practice, if I chose a tube to make a level bridge, I should always be able to set my custom tube in some new window (or part of an existing window) by choosing which level, as happens now with a button, and entering the data X and Y to tell exactly where to go out in the level and all, like Mario's type of movement and behavior.

On the surface it looks stupid but it didn't end there, that's why it's not stupid.

There should be three modes of choice for pipes:

1)
Pipes leading to other levels must then be specified:

as is currently the case but with the possibility of making more of these solts in different levels.

---

2)
Pipes "ignore bridges"

Pipes that in the jump options take into account as "default" the same level where you are (alternatively, to correct it would be enough to select the level you are modifying or delete the "jump" to create a new one)

---

3)
Pipes leading to the map

Instead for the pipes that necessarily need the enemy who decides the position on the map, the enemy could be eliminated in the list of "enemy" icons in the window and it would function via tip [✓] "adding an enemy in the orange list at the top" an action equal to that occurs for the enemy of the "level scroll".

--------

All these changes would be handled simply, as I think you might guess, in the window
"Jump Editor" (that is used to manage level jumps) for each custom bridge, so as to make everything easier.
At each selection of the "Add Jump" button you could assign any pipe that is part of the pipes dedicated to level jumps, meaning the "can go" pipes only by setting the window, as currently happens, by adding only a new button in the GUI for each tube to be set which sends to the list of levels.

The slightly more complicated problem would perhaps only be when you should decide the jump in the map, which as we know, should only take into account a right and a left (an entrance and an exit, for each set of tubes),
but nothing complicated, I have an idea about it.

You could simply adopt the destination method, meaning without considering the entry claim but always and only the destination, so as to set, simply as is currently the case, each entry and exit managing only the exits in the level changes, (temporarily given there is no Internal Map Editor in Foundry and in any case it would be complicated to think of one for the pipe setting discourse).

Taking this into account, we could only allocate the destinations (exits) on the map, and by doing this we would make it so, just to give an example, that by modifying the "pipe 1 end 1" level we would exit in the "pipe 1 end 2" level. , so if we wanted to do the opposite it would be enough to enter the level where we would have decided the initial exit in the example to set the other exit, which in this case would replace the entry.
If "pipe 1 end 1" or "pipe 1 end 2" were an entry or exit name it would not matter, it would be handled by the system.

Knowing this we could do in order to differentiate this setting mode, as I said much before, through a tip [✓], which would increase the orange level in the upper right dedicated to the enemies as it is necessary to add an enemy for the function skip level.
The tip "[✓]" should obviously be in the window
"Jump Editor" to change the type of jump, and if this type of jump is decided, the system should behave in such a way that, as soon as I press the button to set the "jump on map" level, it temporarily removes the window in front of me, waiting for my input , the action should consist of choosing the "can go" pipe not yet used inside the level to be able to automatically build the enemy for the function, which would be invisible and managed by the system, after choosing this I should be able to choose the level of exit from the window dedicated to the level list so that the fate of that pipe is to exit in that level with those X and Y coordinates and with that chosen movement of Mario will have to be displayed in the game.
This is missing a piece of the puzzle, the choice of the set of tubes.
We know they are in pairs with the inlets and outlets described as left and right pipes.
This conception in my idea may change, no longer how it works in Map Editor benef. we all use, but with a new method from Foundry, which divides the sets of pairs of tubes into single tubes, as well as having more tubes used because it would double the tubes, this innovative idea would make it possible to set more different destinations on the map without the binding entry and exit obligation for each tube set currently settable in the Benef Map Editor.
If this idea could work then I believe that in the Foundry "Jump Editor" window in addition to the flagship option [✓] you could add a drop-down menu to select the tube set, which I remember in this case the total number would be double than the current ones.
The menu could be placed side by side with the flagship option "[✓]" and be available only when choosing "✓".

All quite simple.

-------
[ Other ]
In the "View" menu of Foundry you could with the "Jump Zones" option active, you could show these areas with a different color to indicate that some areas are different from the others, and that they are dedicated, as in this case, to you jump on the map and no more at level jumps.
A color for the jumps on the map would be appropriate,
the current red for those of level change, and add a third in case of jump on the same level, so that all types are clearly distinguished.

Consideration of the jumping areas:

It is a bit strange to have to necessarily use a 16 X width to identify a jump zone, a single X or two would not be better if feasible?

------------

**Comment by mchlnix** [comment]
What you describe here is a limitation of the ROM, not of the editor. The Jump zones aren't 16 blocks, because I felt like they should be, but because they are in the game.

So the changes you propose would have to be made by changing the actual game, not the editor.
