### ISSUE TITLE
Change functionality drop-down menu for item / enemy selection

### ISSUE THREAD

**Issue by Dariosky-01** [mchlnix/SMB3-Foundry#119]
This menu tool located at the top right that contains all kinds of things of each level set and therefore objects, enemies and enemies that serve the functionality of the game, has a particular, if I click with the mouse there with the left button to search by pressing a letter in the hope that automatically looking for me an object or an enemy that comes first by name ranking, this does not happen.
Unfortunately this way of searching has helped me a lot over time but this does not work it has only given me annoyances and slowdowns, the only problem is that instead of searching once clicked there, it changes the alphanumeric string associated with the first selected object or enemy, I can even delete all the name of something there, nothing changes this action, obviously opening the menu any modification will disappear but this way of working will have made sure to "put a spoke in the wheels".

It would be necessary for the drop-down menu to have blocked names, no longer editable from the keyboard, this would allow an automatic search without opening the menu only by selecting it,
because the only way to get rid of this problem currently is to open the menu to search like this.

Currently the search there works or I open and search with the letters of the keyboard, or I select the menu and press the up and down arrows for the single movements inside without opening in the changes of things up or down with respect to the current selection then, to do it short, I recommend a name change block and a way that allows you to select the contents of the menu without opening it so that pressing a letter works the same way as when it is open.

**Comment by Dariosky-01** [comment]
![Probl](https://user-images.githubusercontent.com/81451904/115774914-79543500-a3b2-11eb-8aed-f8dfe8ba4c44.png)
This is what happens in the drop-down menu.

**Comment by mchlnix** [comment]
The objects are in their inherent order as they appear in the object set. They could be ordered alphabetically, but I'm not sure the effort would be worth it. I cannot replicate the error in your screenshot.
