### ISSUE TITLE
Remove graphic set from Level Header Editor / Add warning for incompatible graphic sets / ...

### ISSUE THREAD

**Issue by PiJoKra** [mchlnix/SMB3-Foundry#125]
You cannot easily change the graphic set of a level, only if the graphic sets are compatible. 
If you want level 1-1 to be a hilly level, the advice has been to use another level, like 1-2, and swap it with level 1-1.

That does make the graphic set setting in the Level Header Editor redundant and also confusing for newcomers.

**Comment by mchlnix** [comment]
You can see the graphics changed in real time, so it should be clear which can be used and which cannot. Since someone might want to change a graphic set to be "Plains 3" or whatever, I would still leave the option there.
