### ISSUE TITLE
Graphics issue

### ISSUE THREAD

**Issue by FLOOFYBULL** [mchlnix/SMB3-Foundry#126]
When the rom is emulated, the graphics look different, such as the nipper plant turning into a top stretch, or the thwomp turning into random enemies, only the graphics are changed, all the enemies behaviors work properly, they just look messed up

**Comment by mchlnix** [comment]
I would need to know what level that was in, if the graphics set was changed in the header editor etc. Also there are enemy incompatibilities, which the warning list should hopefully show. But maybe didn't.
