### ISSUE TITLE
A problem when resetting the visual style from "Dracula" to "Retro".

### ISSUE THREAD

**Issue by Dariosky-01** [mchlnix/SMB3-Foundry#138]
As you can see in the video below starting from the "Retro" visualization style to change it to "Dracula" everything is fine, but if I return the window of the objects and enemies on the left remains Dracula style when it is in the foreground, when there is a window and must necessarily be in the background seems to be restored.

https://user-images.githubusercontent.com/81451904/139581504-d2a3c998-0f33-4446-a66e-8b1b64aa4098.mp4

**Comment by mchlnix** [comment]
Thanks for reporting this. I could not reproduce this and the dracula style method is a bit janky. I might look into a different way to implement a dark mode.
