### ISSUE TITLE
Emulator isn't working

### ISSUE THREAD

**Issue by DriftWare07** [mchlnix/SMB3-Foundry#139]
This is probably with the way I set it up, but when I try to test a level, it gives a win error saying that the emulator command didn't work.

**Comment by DriftWare07** [comment]
What emulatr neds to be intalled?

**Comment by mchlnix** [comment]
I think the default is fceux, but in the settings you can change that. First you need to figure out where the `.exe` file for your emulator is, probably somewhere in the `C:\Programs` folder or something.
If you have a shortcut for it on your desktop, you can right click onto it and under properties, it should show you the location.

If you copy that and replace the "fceux" or whatever it is with it, it should work. Make sure that the `%f` is still part of it.

I don't use Windows, so there might be some more tricks to it. If it still doesn't work for you, you'll find people using it on Windows on the SMB3 Romhacking discord, who can help you better: https://discord.gg/jjaxVNhKyX

**Comment by DriftWare07** [comment]
How would I make it work with mesen? For now, it throws an error when I do a level test [Critical error (UnableToStartMissingDependancies]

**Comment by mchlnix** [comment]
That kinda sounds like your mesen install is broken. Can you open it normally? What is the command you put into the settings

**Comment by DriftWare07** [comment]
Mesen appears to work normally when opened and used manually.
Path to exe: E:/Users/Username/Documents/Mesen.exe
Command Arguements : %f

**Comment by DriftWare07** [comment]
so the total command comes out as : E:/Users/Username/Mesen.exe %f

**Comment by mchlnix** [comment]
Shouldn't it be backslashes on Windows? So "E:\Users\Username\Mesen.exe" ?

**Comment by DriftWare07** [comment]
That's a typo from me, I think

**Comment by mchlnix** [comment]
Can you copy the total command into the cmd.exe prompt in Windows and see if that works? Just replace the %f with the path to a rom file. But since I don't really use Windows, I think checking at the discord is your best bet. Surely someone there is also using Mesen.
