### ISSUE TITLE
Foundry: Bug: Level jumps are broken

### ISSUE THREAD

**Issue by opsodps** [mchlnix/SMB3-Foundry#165]
Version: 1.3 Kawaguchiko

Process to reproduce the issue from a fresh ROM:
1. Enable level parsing.
1. Open World 1-1.
2. Set World 1-2 as the jump location.
3. Set World 1-1 as the jump location from 1-2.
4. World 1-1 now jumps to a corrupted level. Repoint it to World 1-2.
5. Now World 1-2 will jump to its original bonus room instead of 1-1, and trying to repoint it again will cause the process to repeat from Step 4, making the levels impossible to link to each other.

Depending on the level, both jumps might become corrupted permanently, or one of the jumps only gets corrupted once and then is fixed after repointing it. Sadly, I don't know what's causing it, but it's preventing me from linking the levels I made.

**Comment by opsodps** [comment]
Update: `nightly 55a2019`

This bug is quite frustrating as the level I made and replaced with World 1-1 keeps getting its jump location set to the default whenever I save literally anything else in the ROM.

**Comment by mchlnix** [comment]
It seems that, when the jump destination changes, we take care of the level jumped from, the level now jumped to, but forget to remove the reference of the original bonus level to the jumped-from level. So the next time levels are moved around, it still thinks it is jumped to from there and reasserts itself.

Oversight.
