### ISSUE TITLE
"Kuribo's Goomba" has the wrong name

### ISSUE THREAD

**Issue by opsodps** [mchlnix/SMB3-Foundry#173]
Version: 1.3 Kawaguchiko

![image](https://github.com/mchlnix/SMB3-Foundry/assets/75006249/5f54f19c-ade4-4d14-860f-658040bb8580)

Kuribo is Goomba in Japanese, so this translates to "Goomba's Goomba". The proper name would be "Kuribo's Shoe" (what the original American SMB3 manual translated it as) or "Goomba's Shoe" (what it's called in modern Mario games).

**Comment by mchlnix** [comment]
That is actually something you can change yourself, if you want. Just change the name in the data/data.dat file

**Comment by opsodps** [comment]
This is a mistake on my part. It actually WAS called "Kuribo's Goomba" in the manual lol.
