### ISSUE TITLE
Ability to input exact coordinates of an object via text field

### ISSUE THREAD

**Issue by opsodps** [mchlnix/SMB3-Foundry#186]
Might be useful for users wanting to fine-tune their levels, and also for getting around these bugs: https://github.com/mchlnix/SMB3-Foundry/issues/167 https://github.com/mchlnix/SMB3-Foundry/issues/168 The field could be located on the right side of the screen with the other object info.

**Comment by mchlnix** [comment]
Those bugs can be fixed, I'm sure. But I'm not opposed to it. I would just wonder how exactly that would work?

Maybe right click on an object/entry in the level list and have a "input coordinates" option? How would that work when having multiple objects selected?

**Comment by opsodps** [comment]
like this as i said in the op

![image](https://github.com/mchlnix/SMB3-Foundry/assets/75006249/282827b6-022e-41fa-84b6-22fb11ab4a30)

**Comment by opsodps** [comment]
You might've misunderstood. I meant that when inputting the coordinates, it would cause the object to move to those coordinates.

**Comment by mchlnix** [comment]
Both bugs that were referenced were fixed and I don't really like that solution of another text entry. I'll close it for now and will reconsider, if I hear about it again based on other problems.
