### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by opsodps** [mchlnix/SMB3-Foundry#189]
Instructions:
1. Parse ROM in Foundry,
2. Copy level/enemy offsets of the World 1 empty underground bonus room (should be the second one on the found levels list).
3. Point World 1-5 to said offsets in Scribe.
4. Re-open ROM in Foundry, re-parse, then try to load the level.

Error:
![image](https://github.com/mchlnix/SMB3-Foundry/assets/75006249/e7019693-fc0e-46d6-bf06-95f1734e0223)
![image-1](https://github.com/mchlnix/SMB3-Foundry/assets/75006249/100d0b66-ff54-4532-974a-7aaa9c2c9b37)

**Comment by mchlnix** [comment]
Thanks for the steps to reproduce. Unfortunately those don't lead to a crash, when I try to reproduce it with a fresh rom.

**Comment by opsodps** [comment]
Guess I should have specified the version, or maybe I got the steps wrong. It was a while ago so I don't remember. Sadly I don't have time to test it again. Do you know what the issue could've been judging from what the error messages said?

**Comment by mchlnix** [comment]
I have half an idea and fixed it. There was a problem before, which probably showed you a warning message, but didn't have any other consequences, so the program continued, thinking the level was loaded correctly and died later.
