### ISSUE TITLE
Downloads for Windows broken

### ISSUE THREAD

**Issue by SilverG8888** [mchlnix/SMB3-Foundry#199]
Downloads
SMB3 Foundry Level Editor: [Linux](https://github.com/mchlnix/SMB3-Foundry/releases/download/1.3.1/linux-smb3-foundry), [Windows](https://github.com/mchlnix/SMB3-Foundry/releases/download/1.3.1/win-smb3-foundry), [OSX](https://github.com/mchlnix/SMB3-Foundry/releases/download/1.3.1/osx-smb3-foundry)
SMB3 Scribe Overworld Editor: [Linux](https://github.com/mchlnix/SMB3-Foundry/releases/download/1.3.1/linux-smb3-scribe), [Windows](https://github.com/mchlnix/SMB3-Foundry/releases/download/1.3.1/win-smb3-scribe), [OSX](https://github.com/mchlnix/SMB3-Foundry/releases/download/1.3.1/osx-smb3-scribe)
Manuals: [SMB3 Foundry](https://github.com/mchlnix/SMB3-Foundry/releases/download/1.3.1/manual-foundry.pdf), [SMB3 Scribe](https://github.com/mchlnix/SMB3-Foundry/releases/download/1.3.1/manual-scribe.pdf)

<img width="572" alt="image" src="https://github.com/user-attachments/assets/ee32fe7f-7881-487f-bf7c-c04eaecddaa3" />

**Comment by mchlnix** [comment]
Thanks, I fixed it.
