### ISSUE TITLE
Autosave on every save-state/undo/redo to a separate ROM in case of a crash.

### ISSUE THREAD

**Issue by mchlnix** [mchlnix/SMB3-Foundry#31]

**Comment by bonimy** [comment]
A better way to do this might be to keep a file that serializes all of the changes made to the ROM. When you load the ROM in the editor, load the companion file to get all of your undo/redo history back. You should also keep a hidden/temp copy of the file that autosaves every five minutes, like Microsoft Word does.

**Comment by mchlnix** [comment]
Now, every time the level is changed (so basically every time an undo/redo worthy change is done), the current base ROM is saved into a hidden directory (which is at the point, that was saved last) and the undo/redo information is also saved, so that the user can restore the level and the state that was open, when the editor crashed.

There will be a messagebox, asking the user, if they want to restore the auto-save ROM on start up. If so, the user will be reminded to save the ROM under a different name and if they try to save to it, they will, again, be reminded to save it under a different name instead.
