### ISSUE TITLE
UI polish and Undo/Redo polish

### ISSUE THREAD

**Issue by BlueFinch3000** [mchlnix/SMB3-Foundry#32]
I know that as a programmer, UI is not top priority, especially when you're in the thick of making it functional. That said, you seem to be nearing that first release version, and i have an idea or two about UI.

1) quick-access toolbar underneath menu (perhaps modeled closely after Workshop, but with fewer green-colored icons, as to avoid confusion). 
2) zoom and undo/redo moved to toolbar
3) header menu cleaned up by sorting the different sections into a tabbed interface. 

also, this isn't a UI issue, but i will include it here:
Undo/redo seems to only be triggered after a copying and pasting, but isn't triggered when you just move an object. It would be useful for any change to be registered so it can be undone or redone (moving an object or enemy, copying and pasting, changes to the header or jumps even?)

**Comment by mchlnix** [comment]
The undo and redo is supposed to work like that, but maybe a bug found its way in there in the mean time.
As for the toolbar, I'll see what I can do, but it's not a priority as long as some features are not yet implemented.

**Comment by mchlnix** [comment]
Undo and redo works again.
