### ISSUE TITLE
Antivirus Avast and VirusTotal consider it to be a trojan!

### ISSUE THREAD

**Issue by GreenCappy** [mchlnix/SMB3-Foundry#46]
Prove me why they aren't.

**Comment by mchlnix** [comment]
The code is right here, if you don't trust the prebuild releases, just run the code yourself. The README has instructions on how to do it.

As to why it is detected as a virus, I don't know. I'm the only contributor, so the only other way to inject malicious code would be when building the thing on the Travis CI server. Highly unlikely someone would go through the trouble for such a small project.

But when in doubt, don't use a file you don't trust. Nothing wrong with that.

**Comment by mchlnix** [comment]
Some more details, regarding 1.0_beta16:

in VirusTotal only 1 out of 58 classifies the linux version as dangerous, 7 out of 72 classify the windows version as dangerous.

It probably has something to do with me using pyinstaller to make the "one-file" versions. They seem to have a small history of false positives with anti virus programs: https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed
