### ISSUE TITLE
List of all Enemys, objects and Items 

### ISSUE THREAD

**Issue by Aaron-Junker** [mchlnix/SMB3-Foundry#47]
[list.xlsx](https://github.com/mchlnix/SMB3-Foundry/files/4343576/list.xlsx)
Add this list of all Enemys, objects and Items to the "docs" folder.

**Comment by Aaron-Junker** [comment]
So is this a no?

**Comment by mchlnix** [comment]
Sorry for not leaving a comment. 

This information is already available in the data/data.dat file. In a weird format, though, sure. The docs folder is a bit of a mess anyway, so if you want it added, feel free to open a Pull Request. Note that I changed the names of some of the objects in the data.dat file.

If some information could be added to the individual objects, like the platforms extending down crashing the game, if they reach the lower level bound, it would be very useful.
