### ISSUE TITLE
"60 Degree platform wire - Down/Right" in graphic set "Ice" is broken in the editor

### ISSUE THREAD

**Issue by PiJoKra** [mchlnix/SMB3-Foundry#54]
When you want to add the _60 Degree platform wire - Down/Right_ and drag it wider than 2 blocks, it takes on the formation of the _60 Degree platform wire - Down/Left_
![image](https://user-images.githubusercontent.com/1878071/84600128-c7311000-ae66-11ea-9b9b-302fe27face9.png)

**Comment by mchlnix** [comment]
fixed
