### ISSUE TITLE
Unknown File in Mac OS

### ISSUE THREAD

**Issue by maxoakland** [mchlnix/SMB3-Foundry#60]
Installation of this program is really complicated on Mac OS

**Comment by mchlnix** [comment]
Have you tried these steps? https://github.com/mchlnix/SMB3-Foundry/blob/master/MANUAL.md#the-easy-way

**Comment by maxoakland** [comment]
Yes, thanks! It works. Are there any plans for a more standard installation? The software is so good but I know a lot of people won't be familiar with that, including me

**Comment by mchlnix** [comment]
I'm not a mac user, so I don't know what a standard installation looks like. What would you suggest/expect?

**Comment by maxoakland** [comment]
There are three typical ways to install software on a mac:
  
1. Drag it from a ZIP file or disk image into the Applications folder where you can double click and run it
  
2. Open an installer .Pkg file that installs more complicated things (I’m guessing this might the the best way for your program) and then run it from the Applications folder in the future
  
3. Install it from the Mac app store
  

  
If you have any more questions I’ll be happy to answer
  

  

  

  
  

  
  
>
