### ISSUE TITLE
Abstract out `MainWindow`'s Menus

### ISSUE THREAD

**Issue by fortenbt** [mchlnix/SMB3-Foundry#63]
As seen partially implemented in https://github.com/TheJoeSmo/SMB3-Foundry/commit/398dd601c0bbac766cebcea007fed421e80d0667, there might be some benefit to abstracting out all the individual `QMenu`s created in [`MainWindow.py`](https://github.com/mchlnix/SMB3-Foundry/blob/ddf3c998c551aa080b4086177f95f7c4d19b6129/foundry/gui/MainWindow.py#L115).

This could clean up the creation of the Menus and might make it more straightforward to edit individual Menus.

I would like some feedback on this, however, since it doesn't really seem to enable any functionality. It might just be some low hanging fruit for someone to pick up and implement as more of a project cleanup issue. Would structuring the code this way really reduce clutter/copy+pasted code that much or facilitate anything like the plugin API?

**Comment by mchlnix** [comment]
So have a LevelMenu class, that has the actions for the level menu in it and then just get's instantiated into MainWindow? Sure. They could have a `enable_actions` function, based on if a ROM is loaded and/or if a level is loaded.

**Comment by mchlnix** [comment]
Partially done, where they could be mostly independent of the main window. Like the View menu.
