### ISSUE TITLE
Allow editing expanded ROMs

### ISSUE THREAD

**Issue by fortenbt** [mchlnix/SMB3-Foundry#67]
**Is your feature request related to a problem? Please describe.**
The editor does not currently support loading a ROM that has had its PRG and/or CHR banks expanded:

![image](https://user-images.githubusercontent.com/1106428/104486262-7e2a7100-5599-11eb-83f9-0cc67b31c479.png)

**Describe the solution you'd like**
The editor should parse what it can out of the iNES header and track and apply this data in a way such that expanded ROMs can be opened successfully.

**Describe alternatives you've considered**
N/A

**Additional context**
Right now, some of the files have hard-coded addresses or offsets specifying a location in the ROM for graphics or tile data.

When expanding the ROM to add PRG banks, the graphics data could shift. We should be able to read the iNES header to know what offset to begin looking for graphics data.

After a quick look through much of loading code, the main culprit is the [`PAGE_A000_ByTileset` constant in `constants.py`](https://github.com/mchlnix/SMB3-Foundry/blob/ddf3c998c551aa080b4086177f95f7c4d19b6129/smb3parse/constants.py#L2787) when [`get_tsa_data` uses it via `TSA_OS_LIST`](https://github.com/mchlnix/SMB3-Foundry/blob/ddf3c998c551aa080b4086177f95f7c4d19b6129/foundry/game/File.py#L46). Bank 30 contains the `PAGE_A000_ByTileset` array the code is using to get the offsets to the TSA data, and bank 30 shifts to bank 62 when the ROM is expanded.

Only correcting the `PAGE_A000_ByTileset` constant value allows Foundry to load the ROM, but the graphics look like:
![image](https://user-images.githubusercontent.com/1106428/104487562-4290a680-559b-11eb-9908-2a2e7a0f1d15.png)

The other problem lies in `GraphicsSet.py`, in the `GraphicsSet` class's [`_read_in_chr_rom_segment` method](https://github.com/mchlnix/SMB3-Foundry/blob/ddf3c998c551aa080b4086177f95f7c4d19b6129/foundry/game/gfx/GraphicsSet.py#L91). This method is using a constant `CHR_ROM_OFFSET` defined at the top of the file. This value should be derived from the iNES header.

Finally, I believe the last problem is also in the `GraphicsSet` class, [where it reads from `Level_BG_Pages1` and `Level_BG_Pages2`](https://github.com/mchlnix/SMB3-Foundry/blob/ddf3c998c551aa080b4086177f95f7c4d19b6129/foundry/game/gfx/GraphicsSet.py#L56). These constants are located in bank 30 and thus must be offset to bank 62 for an expanded ROM.

**Comment by mchlnix** [comment]
Since the MR was merged, I guess this is fixed.
