### ISSUE TITLE
Switching Between Vertical and Horizontal Make Objects Unreachable

### ISSUE THREAD

**Issue by TheJoeSmo** [mchlnix/SMB3-Foundry#72]
**Describe the bug**
When switching the level between horizontal and vertical the level editor makes it impossible to move objects that were cut off due to the switch from horizontal to vertical or vise versa.

**To Reproduce**
1. Open 1-1 or 7-1
2. Open the `Level` > `Edit Header`
3. Click on `Level is Vertical`

**Expected behavior**
The objects should be movable or be relocated appropriately.  

**Screenshots**
![image](https://user-images.githubusercontent.com/44075777/104835049-e1562500-5871-11eb-8a84-fda87321ba5a.png)
![image](https://user-images.githubusercontent.com/44075777/104835062-f8951280-5871-11eb-8d42-708e41eaedc1.png)

**Comment by mchlnix** [comment]
When this happens a warning is added to the warning list. The warning is pointing to the object, which can be reached and deleted through the object list on the right.
