### ISSUE TITLE
Mac build is not usable

### ISSUE THREAD

**Issue by Funnylinkk** [mchlnix/SMB3-Foundry#79]
The Mac version is compiled into a .dms file. This is not a common file type and is not usable.

**Comment by fortenbt** [comment]
From: https://discussions.apple.com/thread/250741530#:~:text=A%20file%20with%20a%20.,The%20.

>A file with a .dms extension is a file that has been downloaded and renamed by the Apple Safari web browser or the Apple Mail email client. It contains the contents of a file that did not have a file extension or was erroneously renamed when downloaded. The .dms extension is a result of a bug in Safari and Mail.

Please let us know if you can simply run the file or rename it and then run it.

**Comment by Funnylinkk** [comment]
Yep, I tried renaming it to .app and .dmg, I'll try naming it .zip.

**Comment by Funnylinkk** [comment]
I have tried renaming it zip, doesn't work. You guys forgot to put the file extension at the end.

**Comment by mchlnix** [comment]
What is the default extension for an executable in Mac OS? What would you expect it to have?

**Comment by Funnylinkk** [comment]
It would be a .dmg file, or maybe a .app File , but I tried that and it has not worked.

**Comment by mchlnix** [comment]
Haven't heard any complaints since and I don't have a mac to test it, so I guess it works, or no one cares enough.
