### ISSUE TITLE
Personalization of worlds to be used with personalized succession

### ISSUE THREAD

**Issue by Dariosky-01** [mchlnix/SMB3-Foundry#93]
Premise:

This text is a translated text so sorry for any mistakes, I did my best, but I am human.
_____________________________________________

Guys, I don't know if my idea can work in Foundry to make it compatible with using Map Editor but I would like to try to talk about my idea.

A guy chatting on Discord had advised me, to have more screenshots in my first world of my rom hack, to change the values ​​in the Hex code to blast world 1 and jump directly to one later, example world 3 which it has 3 map screens (in case you want 3 screens).
The consequence of this, according to what he told me, is to have fewer worlds available (I deduce logically) because as "world 4" said, in the example, if my first world had been set in the third at the beginning of the game, it would have become my world 2 of my rom hack and obviously to follow all the others in this logical deductible way.

Now all this has given me an idea ...
The idea was for a change in Foundry without taking away the ability to use the map editor to edit the map view.

All this change could be implemented there in this way on Foundry and have, inside a window with miscellaneous option, a way that is a miscellaneous option to set the worlds that you want to have in the SMB3 game file that I would like to modify (I speak so why is it my current problem)

The idea would be to put more white curtain menus (like the world choice one in Map Editor) related to this change in miscellaneous options, and it should look more or less like this ...
in original form without changes in the file meaning once opened and with an original file or in any case that has those original values ​​in the internal code not changed through the hex code editor, here's how
I imagine it inside a window and in its relative optional card dedicated to this modification: 

1 - [World 1] [V]
2 - [World 2] [V]
3 - [World 3] [V]
4 - [World 4] [V]
5 - [World 5] [V]
6 - [World 6] [V]
7 - [World 7] [V]
8 - [World 8] [V]

Now the idea would be that those white drop-down menus you see would contain the one world location sets for each playable world Mario would enter after killing the last memic of the last SMB3 world castle that would pass the most (+) window modification that appears before you can play in the world and subsequent worlds, specifically meaning that the notification relating to the name of the world inside the window should change, otherwise the window would say something wrong, for example if I set world 3 as my personal world 1 in my rom hack should not appear world 3 but world 1 in the world notification window before using Mario in the map during the game.

Then the letters of the princess should also follow my setting, then speaking specifically of the letter of world 7, which as far as I remember does not show the princess but Bowser, this special letter should always appear in the penultimate world I would choose to have in the setting to be consistent with originally created system to then find Bowser in the last world and finish the game

For example, if I wanted only three worlds and in different sequence I would have to have in detail in the miscellaneous edit window for this problem a modification of this type for only 3 worlds to be used in my personal hack rom:

1 - [World 0] [V]
2 - [World 0] [V]
3 - [World 1] [V]
4 - [World 3] [V]
5 - [World 2] [V]
6 - [World 0] [V]
7 - [World 0] [V]
8 - [World 0] [V]

In this hypothetical case of custom set Mario should immediately appear in world 3 as if it were the first world, both for the world notification start window and for the letter of the princess and in this case have as bowser's letter (the same as the one you find in the world 7 after killing the enemy in the last castle appears in the original game if I'm not mistaken) in the end second world modified in the options, which in this case in the example above would be world 5.

Obviously in the window I could not choose more than one world 1, or 2, or 3, or more, if already a set for world 1 existed while trying to set another one for world 1 in another small white curtain menu, that than before, at this point it should only automatically set to zero if you try, meaning it would not be used in the game.

However, if I started to change at least one drop-down all these menu values ​​should automatically set to "zero" inside the munus if I tried to open one, and I should have only 1 and 0 as the first options when opening any menu once everything is zero, that is, what I would try to open one. If the first world was already set then in the list I could choose it should be only between 0, 1 or 2, just so you can avoid errors and obviously the others to follow with the same system.
However, if at the time of choosing the second world, therefore having only 0,1 or 2 available as options, if you search again for the value 1 set before in another menu, the previous one should return to 0.

At this point graphically to modify the maps it would not be difficult (perhaps, as long as everything goes smoothly) it would be enough to set world 3 in Map Editor to modify my world 1, set world 5 in Map Editor to modify my world 2 and world 4 for my last world where I would put Bowser.

Obviously it would be nice if you could also choose the music in another miscellany option with this set of menus obviously in this other different option it could be possible to have more than one world music the same for multiple worlds, so there would be no need for that logical technique , that first ploy to avoid mistakes) at most it would be right to add another menu for world music 9.

**Comment by mchlnix** [comment]
You can now change the order of the worlds in Scribe. You can't remove worlds, but just move the ones you want to the front and ignore the other ones.
