### ISSUE TITLE
Bugs of different versions in Win7 (with specifications)

### ISSUE THREAD

**Issue by Dariosky-01** [mchlnix/SMB3-Foundry#99]
Hello everyone.

I have encountered several bugs in
start-up phase in the
different versions of
Foundy currently
present on the site
with my pc with
windows 7 Ultimate
64 bit

The only version that starts
is:

Osaka beta21
obviously 64bit.

The different versions have
in common that initiate an output
with a similar error window
to others and someone with a mistake
different, the latest alpha version
he only has a small childbirth
different but then for the rest
are errors the same as yes
present by opening the version
at 32bit in this pc at 64.

Now I will list the different errors
writing what I see written in the messages
and I will write "* 1" and "* 2" to associate
understanding that the error message is the same,
and with the letters "A" and "B" whichever appears first.

-------------------
Types of errors:
-------------------
Error 1: (* 1) A

Unable to start the program because
api-ms-win-crt-runtime- | 1-1-0.dll is not
present in the computer. To resolve the
problem, try reinstalling the program.

--------------------

Error 2: (* 1) B.

Error loading Python DLL
'C: \ Users \ Dario \ Local \ Temp \ _MEI22042 \ python38.dll'.
LoadLibrary: The specified module could not be found.

--------------------

Error 3: (* 2) unique

Failed to execute script pyi_rth_mutiprocessing.

--------------------
=======

- 32bit Osaka beta21
* 1 A, B

- 64bit Osaka beta21

- It works.

========

- 32bit Tokio beta22
* 1 A, B

- 64bit Tokio beta22
* 2

========

- 32bit Sappro beta23
* 1 A, B

- 64bit Sappro beta23
* 2

========

- 32bit NightlyNightly Alpha
* 1 A, B*

- 64bit NightlyNightly Alpha
* 1 A, B*

Please note:
here the name in the path written in the message "B*"
change from "python38.dll" to "python39.dll".

========

System Info:

Win7 Ultimate 64bit
1.0 GB Ram
Intel (R) Atom (TM) CPU N570 processor @ 1.66GHz -1.67GHz

565MB available on Hard Disk
(64bit Osaka beta21 version works and opens)

========

Draw your own conclusions.

**Comment by mchlnix** [comment]
Thanks for the detailed info. I had to abandon 32bit versions of the editor, so I hope everything works out now.
